// Code generated by goyacc -o ./parser.go parser.y. DO NOT EDIT.

//line parser.y:1

package parser

import __yyfmt__ "fmt"

//line parser.y:3

import (
	"fmt"
	"nodora.org/nodora/internal/ast"
)

//line parser.y:11
type yySymType struct {
	yys    int
	str    string
	node   ast.Node
	nodes  []ast.Node
	signal *ast.Signal
	rule   *ast.Rule
	param  ast.Param
	params []ast.Param
	stmt   ast.Statement
	stmts  []ast.Statement
	expr   ast.Expr
	exprs  []ast.Expr
	span   ast.Span
	prop   ast.ObjectProperty
	props  []ast.ObjectProperty
}

const IDENT = 57346
const STRING = 57347
const NUMBER = 57348
const TRUE = 57349
const FALSE = 57350
const SIGNAL = 57351
const RULE = 57352
const EMIT = 57353
const WHEN = 57354
const OUT = 57355
const IN = 57356
const IF = 57357
const THEN = 57358
const ELSE = 57359
const LPAREN = 57360
const RPAREN = 57361
const LBRACE = 57362
const RBRACE = 57363
const LBRACKET = 57364
const RBRACKET = 57365
const COLON = 57366
const COMMA = 57367
const QMARK = 57368
const DOT = 57369
const NAMESPACE = 57370
const PLUS = 57371
const MINUS = 57372
const STAR = 57373
const SLASH = 57374
const MOD = 57375
const GT = 57376
const LT = 57377
const GTE = 57378
const LTE = 57379
const EQ = 57380
const NEQ = 57381
const AND = 57382
const OR = 57383
const NOT = 57384
const ASSIGN = 57385
const PIPE = 57386

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"STRING",
	"NUMBER",
	"TRUE",
	"FALSE",
	"SIGNAL",
	"RULE",
	"EMIT",
	"WHEN",
	"OUT",
	"IN",
	"IF",
	"THEN",
	"ELSE",
	"LPAREN",
	"RPAREN",
	"LBRACE",
	"RBRACE",
	"LBRACKET",
	"RBRACKET",
	"COLON",
	"COMMA",
	"QMARK",
	"DOT",
	"NAMESPACE",
	"PLUS",
	"MINUS",
	"STAR",
	"SLASH",
	"MOD",
	"GT",
	"LT",
	"GTE",
	"LTE",
	"EQ",
	"NEQ",
	"AND",
	"OR",
	"NOT",
	"ASSIGN",
	"PIPE",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.y:437

type ParserError struct {
	line      int
	col       int
	lastError string
}

func (pe ParserError) Error() string {
	return fmt.Sprintf("%d:%d: %s", pe.line, pe.col, pe.lastError)
}

func Parse(input string) (*ast.Program, error) {
	l := newLexer(input)
	p := yyNewParser()

	if p.Parse(l) != 0 {
		return nil, &ParserError{
			l.line,
			l.col,
			l.lastError,
		}
	}

	return l.result, nil
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 178

var yyAct = [...]uint8{
	82, 33, 41, 80, 84, 42, 43, 38, 36, 55,
	28, 58, 37, 61, 47, 49, 48, 50, 51, 39,
	19, 64, 65, 66, 67, 35, 59, 112, 54, 31,
	53, 14, 52, 120, 62, 63, 60, 69, 70, 90,
	45, 71, 72, 73, 75, 19, 122, 79, 116, 74,
	76, 77, 44, 111, 32, 87, 88, 78, 113, 91,
	89, 12, 114, 115, 57, 135, 124, 118, 92, 15,
	95, 96, 102, 103, 94, 101, 108, 104, 105, 106,
	117, 18, 123, 110, 97, 98, 99, 100, 56, 27,
	11, 119, 131, 93, 121, 68, 47, 49, 48, 50,
	51, 129, 6, 7, 85, 86, 109, 107, 16, 30,
	54, 24, 53, 125, 52, 29, 127, 128, 26, 126,
	25, 10, 130, 9, 1, 83, 3, 132, 20, 8,
	133, 81, 46, 134, 47, 49, 48, 50, 51, 47,
	49, 48, 50, 51, 40, 35, 34, 17, 54, 23,
	53, 22, 52, 54, 21, 53, 13, 52, 5, 4,
	45, 2, 0, 0, 0, 45, 0, 0, 0, 0,
	0, 0, 44, 0, 0, 0, 0, 44,
}

var yyPact = [...]int16{
	93, -1000, 93, -1000, -1000, -1000, 119, 117, -1000, 72,
	41, 104, -1000, 62, 20, -1000, -1000, 107, -1000, 104,
	-1000, -1000, -1000, -1000, -33, 111, 105, -1000, 10, -34,
	70, -1000, 104, -1000, -15, 10, -27, -4, -13, 81,
	8, 11, -1000, 22, 135, 135, -1000, 29, -1000, -1000,
	-1000, -1000, 10, 100, 10, 10, 10, -5, 10, 135,
	77, 135, 135, 135, 135, 135, 135, 135, 92, 135,
	135, 135, 135, 135, 103, 10, -1000, -1000, 102, 10,
	30, 2, -1000, 37, -1000, 39, 24, 61, -1000, 48,
	10, 9, -27, 10, -4, -13, -13, 81, 81, 81,
	81, 22, 11, 11, -1000, -1000, -1000, -1000, 23, 64,
	47, -1000, 10, -1000, 100, 10, 10, -1000, 89, -1000,
	130, 75, -1000, 10, -1000, -1000, -1000, -1000, -1000, 10,
	-1000, 130, 46, -1000, -1000, -1000,
}

var yyPgo = [...]uint8{
	0, 126, 161, 159, 158, 69, 31, 156, 154, 151,
	149, 147, 0, 1, 146, 8, 12, 7, 19, 144,
	2, 5, 6, 132, 131, 3, 4, 125, 124,
}

var yyR1 = [...]int8{
	0, 28, 2, 2, 1, 1, 3, 4, 5, 6,
	6, 7, 7, 11, 11, 8, 8, 9, 9, 10,
	10, 12, 12, 13, 13, 13, 14, 14, 15, 15,
	16, 16, 16, 17, 17, 17, 17, 17, 18, 18,
	19, 19, 19, 19, 20, 20, 20, 21, 21, 21,
	22, 22, 22, 22, 22, 23, 23, 23, 23, 23,
	23, 23, 23, 25, 25, 24, 24, 26, 26, 27,
	27,
}

var yyR2 = [...]int8{
	0, 1, 2, 1, 1, 1, 5, 5, 1, 1,
	3, 0, 1, 0, 2, 1, 1, 3, 4, 7,
	5, 4, 1, 1, 6, 5, 3, 1, 3, 1,
	3, 3, 1, 3, 3, 3, 3, 1, 3, 1,
	3, 3, 3, 1, 3, 3, 1, 1, 2, 2,
	1, 6, 4, 3, 4, 1, 1, 1, 1, 1,
	3, 3, 3, 0, 1, 1, 3, 3, 3, 1,
	3,
}

var yyChk = [...]int16{
	-1000, -28, -2, -1, -3, -4, 9, 10, -1, 4,
	4, 18, 20, -7, -6, -5, 4, -11, 19, 25,
	21, -8, -9, -10, 4, 13, 11, -5, 43, 4,
	4, -12, 44, -13, -14, 15, -15, -16, -17, -18,
	-19, -20, -21, -22, 42, 30, -23, 4, 6, 5,
	7, 8, 22, 20, 18, 43, 18, -6, 26, 41,
	-12, 40, 38, 39, 34, 35, 36, 37, 14, 29,
	30, 33, 31, 32, 27, 22, -21, -21, 28, 18,
	-25, -24, -12, -27, -26, 4, 5, -12, -12, -25,
	44, -12, -15, 16, -16, -17, -17, -18, -18, -18,
	-18, -22, -20, -20, -21, -21, -21, 4, -12, 4,
	-25, 23, 25, 21, 25, 24, 24, 19, 19, -12,
	24, -12, 23, 18, 19, -12, -26, -12, -12, 12,
	-13, 17, -25, -12, -13, 19,
}

var yyDef = [...]int8{
	0, -2, 1, 3, 4, 5, 0, 0, 2, 0,
	0, 11, 13, 0, 12, 9, 8, 0, 6, 0,
	7, 14, 15, 16, 0, 0, 0, 10, 0, 0,
	0, 17, 0, 22, 23, 0, 27, 29, 32, 37,
	39, 43, 46, 47, 0, 0, 50, 55, 56, 57,
	58, 59, 63, 0, 0, 0, 63, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 48, 49, 0, 63,
	0, 64, 65, 0, 69, 0, 0, 0, 18, 0,
	0, 0, 26, 0, 28, 30, 31, 33, 34, 35,
	36, 38, 40, 41, 42, 44, 45, 53, 0, 0,
	0, 60, 0, 61, 0, 0, 0, 62, 20, 21,
	0, 0, 54, 63, 52, 66, 70, 67, 68, 0,
	25, 0, 0, 19, 24, 51,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:63
		{
			yylex.(*lexer).result = &ast.Program{Decls: yyDollar[1].nodes}
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:68
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[2].node)
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:70
		{
			yyVAL.nodes = []ast.Node{yyDollar[1].node}
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:75
		{
			yyVAL.node = yyDollar[1].signal
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:77
		{
			yyVAL.node = yyDollar[1].rule
		}
	case 6:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:82
		{
			yyVAL.signal = &ast.Signal{Name: yyDollar[2].str, Params: yyDollar[4].params}
			yyVAL.signal.Span = yyDollar[1].span.Merge(yyDollar[5].span)
		}
	case 7:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:90
		{
			yyVAL.rule = &ast.Rule{Name: yyDollar[2].str, Statements: yyDollar[4].stmts}
			yyVAL.rule.Span = yyDollar[1].span.Merge(yyDollar[5].span)
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:98
		{
			yyVAL.param = ast.Param{Name: yyDollar[1].str}
			yyVAL.param.Span = yyDollar[1].span
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:106
		{
			yyVAL.params = []ast.Param{yyDollar[1].param}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:108
		{
			yyVAL.params = append(yyDollar[1].params, yyDollar[3].param)
		}
	case 11:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:113
		{
			yyVAL.params = []ast.Param{}
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:115
		{
			yyVAL.params = yyDollar[1].params
		}
	case 13:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:120
		{
			yyVAL.stmts = []ast.Statement{}
		}
	case 14:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:122
		{
			yyVAL.stmts = append(yyDollar[1].stmts, yyDollar[2].stmt)
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:127
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:129
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:134
		{
			a := &ast.Assignment{Name: yyDollar[1].str, Expr: yyDollar[3].expr, IsOut: false}
			a.Span = yyDollar[1].span.Merge(yyDollar[3].expr.GetSpan())
			yyVAL.stmt = a
		}
	case 18:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:140
		{
			a := &ast.Assignment{Name: yyDollar[2].str, Expr: yyDollar[4].expr, IsOut: true}
			a.Span = yyDollar[1].span.Merge(yyDollar[4].expr.GetSpan())
			yyVAL.stmt = a
		}
	case 19:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.y:149
		{
			e := &ast.EmitStatement{Signal: yyDollar[2].str, Args: yyDollar[4].exprs, Condition: yyDollar[7].expr}
			e.Span = yyDollar[1].span.Merge(yyDollar[7].expr.GetSpan())
			yyVAL.stmt = e
		}
	case 20:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:155
		{
			e := &ast.EmitStatement{Signal: yyDollar[2].str, Args: yyDollar[4].exprs}
			e.Span = yyDollar[1].span.Merge(yyDollar[5].span)
			yyVAL.stmt = e
		}
	case 21:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:164
		{
			le := &ast.LambdaExpr{Params: yyDollar[2].params, Body: yyDollar[4].expr}
			le.Span = yyDollar[1].span.Merge(yyDollar[4].expr.GetSpan())
			yyVAL.expr = le
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:170
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:175
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 24:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:177
		{
			c := &ast.ConditionalExpr{Cond: yyDollar[2].expr, Then: yyDollar[4].expr, Else: yyDollar[6].expr}
			c.Span = yyDollar[1].span.Merge(yyDollar[6].expr.GetSpan())
			yyVAL.expr = c
		}
	case 25:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:183
		{
			c := &ast.ConditionalExpr{Cond: yyDollar[1].expr, Then: yyDollar[3].expr, Else: yyDollar[5].expr}
			c.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[5].expr.GetSpan())
			yyVAL.expr = c
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:192
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "||", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:198
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:203
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "&&", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:209
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:214
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "==", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:220
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "!=", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:226
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:231
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: ">", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:237
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "<", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:243
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: ">=", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:249
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "<=", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:255
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:260
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "in", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:266
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:271
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "+", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:277
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "-", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:283
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "%", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:289
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:294
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "*", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:300
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "/", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:306
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:311
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 48:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:313
		{
			u := &ast.UnaryExpr{Op: "!", Expr: yyDollar[2].expr}
			u.Span = yyDollar[1].span.Merge(yyDollar[2].expr.GetSpan())
			yyVAL.expr = u
		}
	case 49:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:319
		{
			u := &ast.UnaryExpr{Op: "-", Expr: yyDollar[2].expr}
			u.Span = yyDollar[1].span.Merge(yyDollar[2].expr.GetSpan())
			yyVAL.expr = u
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:328
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 51:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:330
		{
			c := &ast.CallExpr{Namespace: yyDollar[1].str, Name: yyDollar[3].str, Args: yyDollar[5].exprs}
			c.Span = yyDollar[1].span.Merge(yyDollar[6].span)
			yyVAL.expr = c
		}
	case 52:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:336
		{
			c := &ast.CallExpr{Name: yyDollar[1].str, Args: yyDollar[3].exprs}
			c.Span = yyDollar[1].span.Merge(yyDollar[4].span)
			yyVAL.expr = c
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:342
		{
			s := &ast.SelectorExpr{Expr: yyDollar[1].expr, Field: yyDollar[3].str}
			s.Span = yyDollar[1].expr.GetSpan() // approx
			yyVAL.expr = s
		}
	case 54:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:348
		{
			i := &ast.IndexExpr{Expr: yyDollar[1].expr, Index: yyDollar[3].expr}
			i.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[4].span)
			yyVAL.expr = i
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:357
		{
			i := &ast.Identifier{Name: yyDollar[1].str}
			i.Span = yyDollar[1].span
			yyVAL.expr = i
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:363
		{
			n := &ast.NumberLiteral{Value: yyDollar[1].str}
			n.Span = yyDollar[1].span
			yyVAL.expr = n
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:369
		{
			s := &ast.StringLiteral{Value: yyDollar[1].str}
			s.Span = yyDollar[1].span
			yyVAL.expr = s
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:375
		{
			b := &ast.BoolLiteral{Value: true}
			b.Span = yyDollar[1].span
			yyVAL.expr = b
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:381
		{
			b := &ast.BoolLiteral{Value: false}
			b.Span = yyDollar[1].span
			yyVAL.expr = b
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:387
		{
			a := &ast.ArrayLiteral{Elements: yyDollar[2].exprs}
			a.Span = yyDollar[1].span.Merge(yyDollar[3].span)
			yyVAL.expr = a
		}
	case 61:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:393
		{
			ol := &ast.ObjectLiteral{Properties: yyDollar[2].props}
			ol.Span = yyDollar[1].span.Merge(yyDollar[3].span)
			yyVAL.expr = ol
		}
	case 62:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:398
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 63:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:403
		{
			yyVAL.exprs = []ast.Expr{}
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:405
		{
			yyVAL.exprs = yyDollar[1].exprs
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:410
		{
			yyVAL.exprs = []ast.Expr{yyDollar[1].expr}
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:412
		{
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[3].expr)
		}
	case 67:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:417
		{
			p := ast.ObjectProperty{Key: yyDollar[1].str, Value: yyDollar[3].expr}
			p.Span = yyDollar[1].span.Merge(yyDollar[3].expr.GetSpan())
			yyVAL.prop = p
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:423
		{
			p := ast.ObjectProperty{Key: yyDollar[1].str, Value: yyDollar[3].expr}
			p.Span = yyDollar[1].span.Merge(yyDollar[3].expr.GetSpan())
			yyVAL.prop = p
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:432
		{
			yyVAL.props = []ast.ObjectProperty{yyDollar[1].prop}
		}
	case 70:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:434
		{
			yyVAL.props = append(yyDollar[1].props, yyDollar[3].prop)
		}
	}
	goto yystack /* stack new state and value */
}
