// Code generated by goyacc -o ./parser.go ./parser.y. DO NOT EDIT.

//line ./parser.y:1

package parser

import __yyfmt__ "fmt"

//line ./parser.y:3

import (
	"fmt"
	"nodora.org/nodora/internal/ast"
)

//line ./parser.y:11
type yySymType struct {
	yys    int
	str    string
	node   ast.Node
	nodes  []ast.Node
	signal *ast.Signal
	rule   *ast.Rule
	param  ast.Param
	params []ast.Param
	stmt   ast.Statement
	stmts  []ast.Statement
	expr   ast.Expr
	exprs  []ast.Expr
	span   ast.Span
	prop   ast.ObjectProperty
	props  []ast.ObjectProperty
	arm    *ast.MatchArm
	arms   []*ast.MatchArm
}

const IDENT = 57346
const STRING = 57347
const NUMBER = 57348
const TRUE = 57349
const FALSE = 57350
const SIGNAL = 57351
const RULE = 57352
const EMIT = 57353
const WHEN = 57354
const OUT = 57355
const IN = 57356
const IF = 57357
const THEN = 57358
const ELSE = 57359
const MATCH = 57360
const LPAREN = 57361
const RPAREN = 57362
const LBRACE = 57363
const RBRACE = 57364
const LBRACKET = 57365
const RBRACKET = 57366
const COLON = 57367
const COMMA = 57368
const QMARK = 57369
const DOT = 57370
const NAMESPACE = 57371
const PLUS = 57372
const MINUS = 57373
const STAR = 57374
const SLASH = 57375
const MOD = 57376
const GT = 57377
const LT = 57378
const GTE = 57379
const LTE = 57380
const EQ = 57381
const NEQ = 57382
const AND = 57383
const OR = 57384
const NOT = 57385
const ASSIGN = 57386
const FATARROW = 57387
const PIPE = 57388

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"STRING",
	"NUMBER",
	"TRUE",
	"FALSE",
	"SIGNAL",
	"RULE",
	"EMIT",
	"WHEN",
	"OUT",
	"IN",
	"IF",
	"THEN",
	"ELSE",
	"MATCH",
	"LPAREN",
	"RPAREN",
	"LBRACE",
	"RBRACE",
	"LBRACKET",
	"RBRACKET",
	"COLON",
	"COMMA",
	"QMARK",
	"DOT",
	"NAMESPACE",
	"PLUS",
	"MINUS",
	"STAR",
	"SLASH",
	"MOD",
	"GT",
	"LT",
	"GTE",
	"LTE",
	"EQ",
	"NEQ",
	"AND",
	"OR",
	"NOT",
	"ASSIGN",
	"FATARROW",
	"PIPE",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line ./parser.y:521

type ParserError struct {
	Pos     *ast.Position `json:"pos"`
	Message string        `json:"message"`
}

func (pe ParserError) Error() string {
	return fmt.Sprintf("%s: %s", pe.Pos.String(), pe.Message)
}

func Parse(input string) (*ast.Program, error) {
	l := newLexer(input)
	p := yyNewParser()

	if p.Parse(l) != 0 {
		return nil, &ParserError{
			Pos:     &ast.Position{Line: l.line, Col: l.col},
			Message: l.lastError,
		}
	}

	return l.result, nil
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 197

var yyAct = [...]uint8{
	85, 33, 43, 127, 83, 87, 44, 40, 45, 37,
	19, 148, 158, 39, 57, 28, 60, 63, 98, 14,
	41, 65, 66, 49, 51, 50, 52, 53, 34, 31,
	93, 61, 72, 73, 35, 116, 62, 38, 56, 61,
	55, 82, 54, 19, 147, 67, 68, 69, 70, 124,
	47, 81, 59, 79, 80, 78, 120, 90, 91, 119,
	77, 94, 46, 92, 135, 32, 115, 64, 74, 75,
	76, 95, 12, 99, 100, 106, 107, 97, 157, 112,
	105, 108, 109, 110, 137, 122, 121, 114, 101, 102,
	103, 104, 145, 15, 123, 117, 146, 125, 18, 118,
	136, 129, 132, 130, 133, 134, 58, 11, 49, 51,
	50, 52, 53, 27, 142, 144, 96, 138, 149, 35,
	140, 141, 38, 56, 139, 55, 143, 54, 131, 71,
	6, 7, 88, 89, 113, 47, 49, 51, 50, 52,
	53, 150, 111, 151, 16, 30, 152, 46, 155, 156,
	154, 56, 29, 55, 10, 54, 9, 3, 1, 159,
	8, 126, 86, 47, 129, 132, 130, 133, 134, 49,
	51, 50, 52, 53, 24, 46, 84, 48, 42, 128,
	36, 26, 153, 25, 56, 17, 55, 23, 54, 22,
	21, 131, 20, 13, 5, 4, 2,
}

var yyPact = [...]int16{
	121, -1000, 121, -1000, -1000, -1000, 152, 150, -1000, 88,
	51, 140, -1000, 78, 17, -1000, -1000, 170, -1000, 140,
	-1000, -1000, -1000, -1000, -29, 148, 141, -1000, 19, -30,
	87, -1000, 140, -1000, -11, 19, -1000, -24, 132, -18,
	10, 115, 2, 36, -1000, 32, 132, 132, -1000, 22,
	-1000, -1000, -1000, -1000, 19, 128, 19, 19, 19, -16,
	19, 132, 100, 132, -3, 132, 132, 132, 132, 132,
	132, 165, 132, 132, 132, 132, 132, 138, 19, -1000,
	-1000, 130, 19, 42, 9, -1000, 73, -1000, 34, 31,
	66, -1000, 65, 19, 24, -24, 19, -18, 97, 10,
	10, 115, 115, 115, 115, 32, 36, 36, -1000, -1000,
	-1000, -1000, 40, 81, 64, -1000, 19, -1000, 128, 19,
	19, -1000, 102, -1000, 104, 98, 70, -1000, -1, -1000,
	-1000, 112, -1000, -1000, -1000, -1000, 19, -1000, -1000, -1000,
	-1000, -1000, 19, -1000, 104, -1000, 160, 19, 19, -1000,
	58, -1000, -1000, -1000, -1000, -1000, -33, -1000, 19, -1000,
}

var yyPgo = [...]uint8{
	0, 157, 196, 195, 194, 93, 19, 193, 190, 189,
	187, 185, 0, 1, 180, 179, 28, 9, 13, 7,
	20, 178, 2, 6, 8, 177, 176, 4, 5, 162,
	3, 161, 158,
}

var yyR1 = [...]int8{
	0, 32, 2, 2, 1, 1, 3, 4, 5, 6,
	6, 7, 7, 11, 11, 8, 8, 9, 9, 10,
	10, 12, 12, 13, 13, 13, 13, 14, 14, 31,
	31, 30, 30, 15, 15, 15, 15, 15, 15, 16,
	16, 17, 17, 18, 18, 18, 19, 19, 19, 19,
	19, 20, 20, 21, 21, 21, 22, 22, 22, 22,
	23, 23, 23, 24, 24, 24, 24, 24, 25, 25,
	25, 25, 25, 25, 25, 25, 27, 27, 26, 26,
	28, 28, 29, 29,
}

var yyR2 = [...]int8{
	0, 1, 2, 1, 1, 1, 5, 5, 1, 1,
	3, 0, 1, 0, 2, 1, 1, 3, 4, 7,
	5, 4, 1, 1, 6, 5, 1, 5, 6, 1,
	3, 3, 5, 1, 1, 2, 1, 1, 1, 3,
	1, 3, 1, 3, 3, 1, 3, 3, 3, 3,
	1, 3, 1, 3, 3, 1, 3, 3, 3, 1,
	1, 2, 2, 1, 6, 4, 3, 4, 1, 1,
	1, 1, 1, 3, 3, 3, 0, 1, 1, 3,
	3, 3, 1, 3,
}

var yyChk = [...]int16{
	-1000, -32, -2, -1, -3, -4, 9, 10, -1, 4,
	4, 19, 21, -7, -6, -5, 4, -11, 20, 26,
	22, -8, -9, -10, 4, 13, 11, -5, 44, 4,
	4, -12, 46, -13, -16, 15, -14, -17, 18, -18,
	-19, -20, -21, -22, -23, -24, 43, 31, -25, 4,
	6, 5, 7, 8, 23, 21, 19, 44, 19, -6,
	27, 42, -12, 41, -16, 39, 40, 35, 36, 37,
	38, 14, 30, 31, 32, 33, 34, 28, 23, -23,
	-23, 29, 19, -27, -26, -12, -29, -28, 4, 5,
	-12, -12, -27, 46, -12, -17, 16, -18, 21, -19,
	-19, -20, -20, -20, -20, -24, -22, -22, -23, -23,
	-23, 4, -12, 4, -27, 24, 26, 22, 26, 25,
	25, 20, 20, -12, 25, -12, -31, -30, -15, 4,
	6, 31, 5, 7, 8, 24, 19, 20, -12, -28,
	-12, -12, 12, -13, 17, 22, 26, 45, 12, 6,
	-27, -12, -13, 22, -30, -12, -12, 20, 45, -12,
}

var yyDef = [...]int8{
	0, -2, 1, 3, 4, 5, 0, 0, 2, 0,
	0, 11, 13, 0, 12, 9, 8, 0, 6, 0,
	7, 14, 15, 16, 0, 0, 0, 10, 0, 0,
	0, 17, 0, 22, 23, 0, 26, 40, 0, 42,
	45, 50, 52, 55, 59, 60, 0, 0, 63, 68,
	69, 70, 71, 72, 76, 0, 0, 0, 76, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 61,
	62, 0, 76, 0, 77, 78, 0, 82, 0, 0,
	0, 18, 0, 0, 0, 39, 0, 41, 0, 43,
	44, 46, 47, 48, 49, 51, 53, 54, 56, 57,
	58, 66, 0, 0, 0, 73, 0, 74, 0, 0,
	0, 75, 20, 21, 0, 0, 0, 29, 0, 33,
	34, 0, 36, 37, 38, 67, 76, 65, 79, 83,
	80, 81, 0, 25, 0, 27, 0, 0, 0, 35,
	0, 19, 24, 28, 30, 31, 0, 64, 0, 32,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:67
		{
			yylex.(*lexer).result = &ast.Program{Decls: yyDollar[1].nodes}
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./parser.y:72
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[2].node)
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:74
		{
			yyVAL.nodes = []ast.Node{yyDollar[1].node}
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:79
		{
			yyVAL.node = yyDollar[1].signal
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:81
		{
			yyVAL.node = yyDollar[1].rule
		}
	case 6:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ./parser.y:86
		{
			yyVAL.signal = &ast.Signal{Name: yyDollar[2].str, Params: yyDollar[4].params}
			yyVAL.signal.Span = yyDollar[1].span.Merge(yyDollar[5].span)
		}
	case 7:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ./parser.y:94
		{
			yyVAL.rule = &ast.Rule{Name: yyDollar[2].str, Statements: yyDollar[4].stmts}
			yyVAL.rule.Span = yyDollar[1].span.Merge(yyDollar[5].span)
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:102
		{
			yyVAL.param = ast.Param{Name: yyDollar[1].str}
			yyVAL.param.Span = yyDollar[1].span
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:110
		{
			yyVAL.params = []ast.Param{yyDollar[1].param}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:112
		{
			yyVAL.params = append(yyDollar[1].params, yyDollar[3].param)
		}
	case 11:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./parser.y:117
		{
			yyVAL.params = []ast.Param{}
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:119
		{
			yyVAL.params = yyDollar[1].params
		}
	case 13:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./parser.y:124
		{
			yyVAL.stmts = []ast.Statement{}
		}
	case 14:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./parser.y:126
		{
			yyVAL.stmts = append(yyDollar[1].stmts, yyDollar[2].stmt)
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:131
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:133
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:138
		{
			a := &ast.Assignment{Name: yyDollar[1].str, Expr: yyDollar[3].expr, IsOut: false}
			a.Span = yyDollar[1].span.Merge(yyDollar[3].expr.GetSpan())
			yyVAL.stmt = a
		}
	case 18:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./parser.y:144
		{
			a := &ast.Assignment{Name: yyDollar[2].str, Expr: yyDollar[4].expr, IsOut: true}
			a.Span = yyDollar[1].span.Merge(yyDollar[4].expr.GetSpan())
			yyVAL.stmt = a
		}
	case 19:
		yyDollar = yyS[yypt-7 : yypt+1]
//line ./parser.y:153
		{
			e := &ast.EmitStatement{Signal: yyDollar[2].str, Args: yyDollar[4].exprs, Condition: yyDollar[7].expr}
			e.Span = yyDollar[1].span.Merge(yyDollar[7].expr.GetSpan())
			yyVAL.stmt = e
		}
	case 20:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ./parser.y:159
		{
			e := &ast.EmitStatement{Signal: yyDollar[2].str, Args: yyDollar[4].exprs}
			e.Span = yyDollar[1].span.Merge(yyDollar[5].span)
			yyVAL.stmt = e
		}
	case 21:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./parser.y:168
		{
			le := &ast.LambdaExpr{Params: yyDollar[2].params, Body: yyDollar[4].expr}
			le.Span = yyDollar[1].span.Merge(yyDollar[4].expr.GetSpan())
			yyVAL.expr = le
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:174
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:179
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 24:
		yyDollar = yyS[yypt-6 : yypt+1]
//line ./parser.y:181
		{
			c := &ast.ConditionalExpr{Cond: yyDollar[2].expr, Then: yyDollar[4].expr, Else: yyDollar[6].expr}
			c.Span = yyDollar[1].span.Merge(yyDollar[6].expr.GetSpan())
			yyVAL.expr = c
		}
	case 25:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ./parser.y:187
		{
			c := &ast.ConditionalExpr{Cond: yyDollar[1].expr, Then: yyDollar[3].expr, Else: yyDollar[5].expr}
			c.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[5].expr.GetSpan())
			yyVAL.expr = c
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:193
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 27:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ./parser.y:198
		{
			m := &ast.MatchExpr{Value: yyDollar[2].expr, Arms: yyDollar[4].arms}
			m.Span = yyDollar[1].span.Merge(yyDollar[5].span)
			yyVAL.expr = m
		}
	case 28:
		yyDollar = yyS[yypt-6 : yypt+1]
//line ./parser.y:204
		{
			m := &ast.MatchExpr{Value: yyDollar[2].expr, Arms: yyDollar[4].arms}
			m.Span = yyDollar[1].span.Merge(yyDollar[6].span)
			yyVAL.expr = m
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:213
		{
			yyVAL.arms = []*ast.MatchArm{yyDollar[1].arm}
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:215
		{
			yyVAL.arms = append(yyDollar[1].arms, yyDollar[3].arm)
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:220
		{
			a := &ast.MatchArm{Pattern: yyDollar[1].expr, Body: yyDollar[3].expr}
			a.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.arm = a
		}
	case 32:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ./parser.y:226
		{
			a := &ast.MatchArm{Pattern: yyDollar[1].expr, Guard: yyDollar[3].expr, Body: yyDollar[5].expr}
			a.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[5].expr.GetSpan())
			yyVAL.arm = a
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:235
		{
			i := &ast.Identifier{Name: yyDollar[1].str}
			i.Span = yyDollar[1].span
			yyVAL.expr = i
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:241
		{
			n := &ast.NumberLiteral{Raw: yyDollar[1].str}
			n.Span = yyDollar[1].span
			yyVAL.expr = n
		}
	case 35:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./parser.y:247
		{
			n := &ast.NumberLiteral{Raw: yyDollar[2].str}
			n.Span = yyDollar[2].span
			u := &ast.UnaryExpr{Op: "-", Expr: n}
			u.Span = yyDollar[1].span.Merge(yyDollar[2].span)
			yyVAL.expr = u
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:255
		{
			s := &ast.StringLiteral{Value: yyDollar[1].str}
			s.Span = yyDollar[1].span
			yyVAL.expr = s
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:261
		{
			b := &ast.BoolLiteral{Value: true}
			b.Span = yyDollar[1].span
			yyVAL.expr = b
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:267
		{
			b := &ast.BoolLiteral{Value: false}
			b.Span = yyDollar[1].span
			yyVAL.expr = b
		}
	case 39:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:276
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "||", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:282
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:287
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "&&", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:293
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:298
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "==", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:304
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "!=", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:310
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:315
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: ">", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:321
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "<", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:327
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: ">=", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:333
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "<=", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:339
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:344
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "in", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 52:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:350
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:355
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "+", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:361
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "-", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:367
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 56:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:372
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "*", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:378
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "/", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:384
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "%", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:390
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:395
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 61:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./parser.y:397
		{
			u := &ast.UnaryExpr{Op: "!", Expr: yyDollar[2].expr}
			u.Span = yyDollar[1].span.Merge(yyDollar[2].expr.GetSpan())
			yyVAL.expr = u
		}
	case 62:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./parser.y:403
		{
			u := &ast.UnaryExpr{Op: "-", Expr: yyDollar[2].expr}
			u.Span = yyDollar[1].span.Merge(yyDollar[2].expr.GetSpan())
			yyVAL.expr = u
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:412
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 64:
		yyDollar = yyS[yypt-6 : yypt+1]
//line ./parser.y:414
		{
			c := &ast.CallExpr{Namespace: yyDollar[1].str, Name: yyDollar[3].str, Args: yyDollar[5].exprs}
			c.Span = yyDollar[1].span.Merge(yyDollar[6].span)
			yyVAL.expr = c
		}
	case 65:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./parser.y:420
		{
			c := &ast.CallExpr{Name: yyDollar[1].str, Args: yyDollar[3].exprs}
			c.Span = yyDollar[1].span.Merge(yyDollar[4].span)
			yyVAL.expr = c
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:426
		{
			s := &ast.SelectorExpr{Expr: yyDollar[1].expr, Field: yyDollar[3].str}
			s.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].span)
			yyVAL.expr = s
		}
	case 67:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./parser.y:432
		{
			i := &ast.IndexExpr{Expr: yyDollar[1].expr, Index: yyDollar[3].expr}
			i.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[4].span)
			yyVAL.expr = i
		}
	case 68:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:441
		{
			i := &ast.Identifier{Name: yyDollar[1].str}
			i.Span = yyDollar[1].span
			yyVAL.expr = i
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:447
		{
			n := &ast.NumberLiteral{Raw: yyDollar[1].str}
			n.Span = yyDollar[1].span
			yyVAL.expr = n
		}
	case 70:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:453
		{
			s := &ast.StringLiteral{Value: yyDollar[1].str}
			s.Span = yyDollar[1].span
			yyVAL.expr = s
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:459
		{
			b := &ast.BoolLiteral{Value: true}
			b.Span = yyDollar[1].span
			yyVAL.expr = b
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:465
		{
			b := &ast.BoolLiteral{Value: false}
			b.Span = yyDollar[1].span
			yyVAL.expr = b
		}
	case 73:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:471
		{
			a := &ast.ArrayLiteral{Elements: yyDollar[2].exprs}
			a.Span = yyDollar[1].span.Merge(yyDollar[3].span)
			yyVAL.expr = a
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:477
		{
			ol := &ast.ObjectLiteral{Properties: yyDollar[2].props}
			ol.Span = yyDollar[1].span.Merge(yyDollar[3].span)
			yyVAL.expr = ol
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:482
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 76:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./parser.y:487
		{
			yyVAL.exprs = []ast.Expr{}
		}
	case 77:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:489
		{
			yyVAL.exprs = yyDollar[1].exprs
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:494
		{
			yyVAL.exprs = []ast.Expr{yyDollar[1].expr}
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:496
		{
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[3].expr)
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:501
		{
			p := ast.ObjectProperty{Key: yyDollar[1].str, Value: yyDollar[3].expr}
			p.Span = yyDollar[1].span.Merge(yyDollar[3].expr.GetSpan())
			yyVAL.prop = p
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:507
		{
			p := ast.ObjectProperty{Key: yyDollar[1].str, Value: yyDollar[3].expr}
			p.Span = yyDollar[1].span.Merge(yyDollar[3].expr.GetSpan())
			yyVAL.prop = p
		}
	case 82:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:516
		{
			yyVAL.props = []ast.ObjectProperty{yyDollar[1].prop}
		}
	case 83:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:518
		{
			yyVAL.props = append(yyDollar[1].props, yyDollar[3].prop)
		}
	}
	goto yystack /* stack new state and value */
}
