// Code generated by goyacc -o ./parser.go -v parser.output ./parser.y. DO NOT EDIT.

//line ./parser.y:2
package parser

import __yyfmt__ "fmt"

//line ./parser.y:2

import (
	"fmt"
	"nodora.org/nodora/internal/ast"
)

//line ./parser.y:11
type yySymType struct {
	yys    int
	str    string
	node   ast.Node
	nodes  []ast.Node
	param  ast.Param
	params []ast.Param
	stmt   ast.Statement
	stmts  []ast.Statement
	expr   ast.Expr
	exprs  []ast.Expr
	span   ast.Span
	prop   ast.ObjectProperty
	props  []ast.ObjectProperty
	arm    *ast.MatchArm
	arms   []*ast.MatchArm
}

const IDENT = 57346
const STRING = 57347
const NUMBER = 57348
const TRUE = 57349
const FALSE = 57350
const NULL = 57351
const SIGNAL = 57352
const RULE = 57353
const CONST = 57354
const EMIT = 57355
const WHEN = 57356
const OUT = 57357
const IN = 57358
const IF = 57359
const THEN = 57360
const ELSE = 57361
const MATCH = 57362
const LPAREN = 57363
const RPAREN = 57364
const LBRACE = 57365
const RBRACE = 57366
const LBRACKET = 57367
const RBRACKET = 57368
const COLON = 57369
const COMMA = 57370
const QMARK = 57371
const DOT = 57372
const NAMESPACE = 57373
const PLUS = 57374
const MINUS = 57375
const STAR = 57376
const SLASH = 57377
const MOD = 57378
const GT = 57379
const LT = 57380
const GTE = 57381
const LTE = 57382
const EQ = 57383
const NEQ = 57384
const AND = 57385
const OR = 57386
const NOT = 57387
const ASSIGN = 57388
const FATARROW = 57389
const PIPE = 57390

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"STRING",
	"NUMBER",
	"TRUE",
	"FALSE",
	"NULL",
	"SIGNAL",
	"RULE",
	"CONST",
	"EMIT",
	"WHEN",
	"OUT",
	"IN",
	"IF",
	"THEN",
	"ELSE",
	"MATCH",
	"LPAREN",
	"RPAREN",
	"LBRACE",
	"RBRACE",
	"LBRACKET",
	"RBRACKET",
	"COLON",
	"COMMA",
	"QMARK",
	"DOT",
	"NAMESPACE",
	"PLUS",
	"MINUS",
	"STAR",
	"SLASH",
	"MOD",
	"GT",
	"LT",
	"GTE",
	"LTE",
	"EQ",
	"NEQ",
	"AND",
	"OR",
	"NOT",
	"ASSIGN",
	"FATARROW",
	"PIPE",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line ./parser.y:560

type ParserError struct {
	Pos     *ast.Position `json:"pos"`
	Message string        `json:"message"`
}

func (pe ParserError) Error() string {
	return fmt.Sprintf("%s: %s", pe.Pos.String(), pe.Message)
}

func Parse(input string) (*ast.Program, error) {
	l := newLexer(input)
	p := yyNewParser()

	if p.Parse(l) != 0 {
		return nil, &ParserError{
			Pos:     &ast.Position{Line: l.line, Col: l.col},
			Message: l.lastError,
		}
	}

	return l.result, nil
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 230

var yyAct = [...]uint8{
	84, 24, 34, 132, 82, 35, 87, 31, 30, 40,
	42, 41, 43, 44, 45, 32, 36, 22, 19, 50,
	169, 158, 26, 117, 126, 29, 48, 61, 47, 28,
	46, 145, 92, 16, 100, 64, 65, 59, 38, 95,
	62, 71, 72, 78, 79, 144, 73, 74, 75, 90,
	37, 81, 60, 23, 157, 60, 66, 67, 68, 69,
	96, 80, 134, 137, 135, 138, 139, 140, 25, 91,
	83, 99, 101, 102, 108, 109, 121, 119, 114, 110,
	111, 112, 103, 104, 105, 106, 116, 107, 50, 77,
	97, 136, 129, 125, 76, 123, 128, 122, 63, 130,
	40, 42, 41, 43, 44, 45, 155, 141, 120, 118,
	156, 15, 167, 26, 161, 18, 29, 48, 142, 47,
	146, 46, 143, 149, 150, 124, 49, 151, 148, 38,
	127, 153, 152, 40, 42, 41, 43, 44, 45, 58,
	14, 37, 154, 98, 23, 146, 26, 160, 70, 29,
	48, 168, 47, 159, 46, 115, 162, 113, 165, 166,
	164, 94, 38, 40, 42, 41, 43, 44, 45, 170,
	171, 88, 89, 93, 37, 7, 8, 9, 88, 89,
	48, 20, 47, 13, 46, 134, 137, 135, 138, 139,
	140, 147, 38, 12, 40, 42, 41, 43, 44, 45,
	11, 55, 1, 3, 37, 163, 10, 131, 85, 86,
	57, 48, 56, 47, 136, 46, 39, 33, 133, 27,
	21, 51, 54, 53, 52, 17, 2, 6, 5, 4,
}

var yyPact = [...]int16{
	165, -1000, 165, -1000, -1000, -1000, -1000, 196, 189, 179,
	-1000, 119, 88, -13, 177, -1000, 96, 104, 60, -1000,
	-1000, 197, -1000, 177, -1000, 8, 96, -1000, -3, 159,
	-6, 19, 132, 9, 12, -1000, 64, 159, 159, -1000,
	30, -1000, -1000, -1000, -1000, -1000, 96, 174, 96, -1000,
	177, -1000, -1000, -1000, -1000, -14, 169, 157, -9, 96,
	159, 125, 159, 11, 159, 159, 159, 159, 159, 159,
	190, 159, 159, 159, 159, 159, 153, 96, -1000, -1000,
	151, 96, 83, 49, -1000, 84, 48, -1000, 70, 68,
	103, -1000, 96, -22, 109, 96, 65, -3, 96, -6,
	58, 19, 19, 132, 132, 132, 132, 64, 12, 12,
	-1000, -1000, -1000, -1000, 81, 97, 100, 17, -1000, 5,
	-1000, 167, 96, 96, -1000, -1000, 96, 96, -1000, 129,
	123, 82, -1000, 7, -1000, -1000, 147, -1000, -1000, -1000,
	-1000, -1000, 96, -1000, 96, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 92, -1000, 129, -1000, 181, 96, 96, -1000,
	90, 137, -1000, -1000, -1000, -1000, -27, -1000, 96, 96,
	-1000, -1000,
}

var yyPgo = [...]uint8{
	0, 203, 229, 228, 227, 226, 18, 115, 225, 224,
	223, 222, 220, 0, 1, 219, 218, 68, 29, 8,
	7, 15, 217, 2, 5, 16, 216, 23, 4, 6,
	209, 208, 3, 207, 202,
}

var yyR1 = [...]int8{
	0, 34, 5, 5, 1, 1, 1, 2, 3, 4,
	6, 7, 7, 8, 8, 12, 12, 9, 9, 10,
	10, 11, 11, 13, 13, 14, 14, 14, 14, 15,
	15, 33, 33, 32, 32, 16, 16, 16, 16, 16,
	16, 16, 17, 17, 18, 18, 19, 19, 19, 20,
	20, 20, 20, 20, 21, 21, 22, 22, 22, 23,
	23, 23, 23, 24, 24, 24, 25, 25, 25, 25,
	25, 26, 26, 26, 26, 26, 26, 26, 26, 26,
	26, 26, 28, 28, 27, 27, 29, 29, 31, 31,
	30, 30,
}

var yyR2 = [...]int8{
	0, 1, 2, 1, 1, 1, 1, 5, 5, 4,
	1, 1, 3, 0, 1, 0, 2, 1, 1, 3,
	4, 7, 5, 4, 1, 1, 6, 5, 1, 5,
	6, 1, 3, 3, 5, 1, 1, 2, 1, 1,
	1, 1, 3, 1, 3, 1, 3, 3, 1, 3,
	3, 3, 3, 1, 3, 1, 3, 3, 1, 3,
	3, 3, 1, 1, 2, 2, 1, 6, 4, 3,
	4, 1, 1, 1, 1, 1, 1, 3, 4, 3,
	4, 3, 0, 1, 1, 3, 3, 3, 0, 1,
	1, 3,
}

var yyChk = [...]int16{
	-1000, -34, -5, -1, -2, -3, -4, 10, 11, 12,
	-1, 4, 4, 4, 21, 23, 46, -8, -7, -6,
	4, -12, -13, 48, -14, -17, 17, -15, -18, 20,
	-19, -20, -21, -22, -23, -24, -25, 45, 33, -26,
	4, 6, 5, 7, 8, 9, 25, 23, 21, 22,
	28, 24, -9, -10, -11, 4, 15, 13, -7, 29,
	44, -13, 43, -17, 41, 42, 37, 38, 39, 40,
	16, 32, 33, 34, 35, 36, 30, 25, -24, -24,
	31, 21, -28, -27, -13, -31, -30, -29, 4, 5,
	-13, -6, 46, 4, 4, 48, -13, -18, 18, -19,
	23, -20, -20, -21, -21, -21, -21, -25, -23, -23,
	-24, -24, -24, 4, -13, 4, -28, -27, 26, 28,
	24, 28, 27, 27, 22, -13, 46, 21, -13, 27,
	-13, -33, -32, -16, 4, 6, 33, 5, 7, 8,
	9, 26, 21, 22, 28, 26, -13, 24, -29, -13,
	-13, -13, -28, -14, 19, 24, 28, 47, 14, 6,
	-28, 22, -14, 24, -32, -13, -13, 22, 14, 47,
	-13, -13,
}

var yyDef = [...]int8{
	0, -2, 1, 3, 4, 5, 6, 0, 0, 0,
	2, 0, 0, 0, 13, 15, 0, 0, 14, 11,
	10, 0, 9, 0, 24, 25, 0, 28, 43, 0,
	45, 48, 53, 55, 58, 62, 63, 0, 0, 66,
	71, 72, 73, 74, 75, 76, 82, 88, 0, 7,
	0, 8, 16, 17, 18, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 64, 65,
	0, 82, 0, 83, 84, 0, 89, 90, 0, 0,
	0, 12, 0, 0, 0, 0, 0, 42, 0, 44,
	0, 46, 47, 49, 50, 51, 52, 54, 56, 57,
	59, 60, 61, 69, 0, 0, 0, 83, 77, 0,
	79, 0, 0, 0, 81, 19, 0, 82, 23, 0,
	0, 0, 31, 0, 35, 36, 0, 38, 39, 40,
	41, 70, 82, 68, 0, 78, 85, 80, 91, 86,
	87, 20, 0, 27, 0, 29, 0, 0, 0, 37,
	0, 22, 26, 30, 32, 33, 0, 67, 0, 0,
	21, 34,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:63
		{
			yylex.(*lexer).result = &ast.Program{Decls: yyDollar[1].nodes}
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./parser.y:68
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[2].node)
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:70
		{
			yyVAL.nodes = []ast.Node{yyDollar[1].node}
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:75
		{
			yyVAL.node = yyDollar[1].node
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:77
		{
			yyVAL.node = yyDollar[1].node
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:79
		{
			yyVAL.node = yyDollar[1].node
		}
	case 7:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ./parser.y:84
		{
			s := &ast.Signal{Name: yyDollar[2].str, Params: yyDollar[4].params}
			s.Span = yyDollar[1].span.Merge(yyDollar[5].span)
			yyVAL.node = s
		}
	case 8:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ./parser.y:93
		{
			r := &ast.Rule{Name: yyDollar[2].str, Statements: yyDollar[4].stmts}
			r.Span = yyDollar[1].span.Merge(yyDollar[5].span)
			yyVAL.node = r
		}
	case 9:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./parser.y:102
		{
			c := &ast.Const{Name: yyDollar[2].str, Value: yyDollar[4].expr}
			c.Span = yyDollar[1].span.Merge(yyDollar[4].expr.GetSpan())
			yyVAL.node = c
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:111
		{
			yyVAL.param = ast.Param{Name: yyDollar[1].str}
			yyVAL.param.Span = yyDollar[1].span
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:119
		{
			yyVAL.params = []ast.Param{yyDollar[1].param}
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:121
		{
			yyVAL.params = append(yyDollar[1].params, yyDollar[3].param)
		}
	case 13:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./parser.y:126
		{
			yyVAL.params = []ast.Param{}
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:128
		{
			yyVAL.params = yyDollar[1].params
		}
	case 15:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./parser.y:133
		{
			yyVAL.stmts = []ast.Statement{}
		}
	case 16:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./parser.y:135
		{
			yyVAL.stmts = append(yyDollar[1].stmts, yyDollar[2].stmt)
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:140
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:142
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:147
		{
			a := &ast.Assignment{Name: yyDollar[1].str, Expr: yyDollar[3].expr, IsOut: false}
			a.Span = yyDollar[1].span.Merge(yyDollar[3].expr.GetSpan())
			yyVAL.stmt = a
		}
	case 20:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./parser.y:153
		{
			a := &ast.Assignment{Name: yyDollar[2].str, Expr: yyDollar[4].expr, IsOut: true}
			a.Span = yyDollar[1].span.Merge(yyDollar[4].expr.GetSpan())
			yyVAL.stmt = a
		}
	case 21:
		yyDollar = yyS[yypt-7 : yypt+1]
//line ./parser.y:162
		{
			e := &ast.EmitStatement{Signal: yyDollar[2].str, Args: yyDollar[4].exprs, Condition: yyDollar[7].expr}
			e.Span = yyDollar[1].span.Merge(yyDollar[7].expr.GetSpan())
			yyVAL.stmt = e
		}
	case 22:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ./parser.y:168
		{
			e := &ast.EmitStatement{Signal: yyDollar[2].str, Args: yyDollar[4].exprs}
			e.Span = yyDollar[1].span.Merge(yyDollar[5].span)
			yyVAL.stmt = e
		}
	case 23:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./parser.y:177
		{
			le := &ast.LambdaExpr{Params: yyDollar[2].params, Body: yyDollar[4].expr}
			le.Span = yyDollar[1].span.Merge(yyDollar[4].expr.GetSpan())
			yyVAL.expr = le
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:183
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:188
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 26:
		yyDollar = yyS[yypt-6 : yypt+1]
//line ./parser.y:190
		{
			c := &ast.ConditionalExpr{Cond: yyDollar[2].expr, Then: yyDollar[4].expr, Else: yyDollar[6].expr}
			c.Span = yyDollar[1].span.Merge(yyDollar[6].expr.GetSpan())
			yyVAL.expr = c
		}
	case 27:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ./parser.y:196
		{
			c := &ast.ConditionalExpr{Cond: yyDollar[1].expr, Then: yyDollar[3].expr, Else: yyDollar[5].expr}
			c.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[5].expr.GetSpan())
			yyVAL.expr = c
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:202
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 29:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ./parser.y:207
		{
			m := &ast.MatchExpr{Value: yyDollar[2].expr, Arms: yyDollar[4].arms}
			m.Span = yyDollar[1].span.Merge(yyDollar[5].span)
			yyVAL.expr = m
		}
	case 30:
		yyDollar = yyS[yypt-6 : yypt+1]
//line ./parser.y:213
		{
			m := &ast.MatchExpr{Value: yyDollar[2].expr, Arms: yyDollar[4].arms}
			m.Span = yyDollar[1].span.Merge(yyDollar[6].span)
			yyVAL.expr = m
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:222
		{
			yyVAL.arms = []*ast.MatchArm{yyDollar[1].arm}
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:224
		{
			yyVAL.arms = append(yyDollar[1].arms, yyDollar[3].arm)
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:229
		{
			a := &ast.MatchArm{Pattern: yyDollar[1].expr, Body: yyDollar[3].expr}
			a.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.arm = a
		}
	case 34:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ./parser.y:235
		{
			a := &ast.MatchArm{Pattern: yyDollar[1].expr, Guard: yyDollar[3].expr, Body: yyDollar[5].expr}
			a.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[5].expr.GetSpan())
			yyVAL.arm = a
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:244
		{
			i := &ast.Identifier{Name: yyDollar[1].str}
			i.Span = yyDollar[1].span
			yyVAL.expr = i
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:250
		{
			n := &ast.NumberLiteral{Raw: yyDollar[1].str}
			n.Span = yyDollar[1].span
			yyVAL.expr = n
		}
	case 37:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./parser.y:256
		{
			n := &ast.NumberLiteral{Raw: yyDollar[2].str}
			n.Span = yyDollar[2].span
			u := &ast.UnaryExpr{Op: "-", Expr: n}
			u.Span = yyDollar[1].span.Merge(yyDollar[2].span)
			yyVAL.expr = u
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:264
		{
			s := &ast.StringLiteral{Value: yyDollar[1].str}
			s.Span = yyDollar[1].span
			yyVAL.expr = s
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:270
		{
			b := &ast.BoolLiteral{Value: true}
			b.Span = yyDollar[1].span
			yyVAL.expr = b
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:276
		{
			b := &ast.BoolLiteral{Value: false}
			b.Span = yyDollar[1].span
			yyVAL.expr = b
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:282
		{
			n := &ast.NullLiteral{}
			n.Span = yyDollar[1].span
			yyVAL.expr = n
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:291
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "||", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:297
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:302
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "&&", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:308
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:313
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "==", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:319
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "!=", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:325
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:330
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: ">", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:336
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "<", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:342
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: ">=", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:348
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "<=", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:354
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:359
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "in", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:365
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 56:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:370
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "+", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:376
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "-", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:382
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:387
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "*", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:393
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "/", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 61:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:399
		{
			b := &ast.BinaryExpr{Left: yyDollar[1].expr, Op: "%", Right: yyDollar[3].expr}
			b.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].expr.GetSpan())
			yyVAL.expr = b
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:405
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:410
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 64:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./parser.y:412
		{
			u := &ast.UnaryExpr{Op: "!", Expr: yyDollar[2].expr}
			u.Span = yyDollar[1].span.Merge(yyDollar[2].expr.GetSpan())
			yyVAL.expr = u
		}
	case 65:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./parser.y:418
		{
			u := &ast.UnaryExpr{Op: "-", Expr: yyDollar[2].expr}
			u.Span = yyDollar[1].span.Merge(yyDollar[2].expr.GetSpan())
			yyVAL.expr = u
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:427
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 67:
		yyDollar = yyS[yypt-6 : yypt+1]
//line ./parser.y:429
		{
			c := &ast.CallExpr{Namespace: yyDollar[1].str, Name: yyDollar[3].str, Args: yyDollar[5].exprs}
			c.Span = yyDollar[1].span.Merge(yyDollar[6].span)
			yyVAL.expr = c
		}
	case 68:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./parser.y:435
		{
			c := &ast.CallExpr{Name: yyDollar[1].str, Args: yyDollar[3].exprs}
			c.Span = yyDollar[1].span.Merge(yyDollar[4].span)
			yyVAL.expr = c
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:441
		{
			s := &ast.SelectorExpr{Expr: yyDollar[1].expr, Field: yyDollar[3].str}
			s.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[3].span)
			yyVAL.expr = s
		}
	case 70:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./parser.y:447
		{
			i := &ast.IndexExpr{Expr: yyDollar[1].expr, Index: yyDollar[3].expr}
			i.Span = yyDollar[1].expr.GetSpan().Merge(yyDollar[4].span)
			yyVAL.expr = i
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:456
		{
			i := &ast.Identifier{Name: yyDollar[1].str}
			i.Span = yyDollar[1].span
			yyVAL.expr = i
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:462
		{
			n := &ast.NumberLiteral{Raw: yyDollar[1].str}
			n.Span = yyDollar[1].span
			yyVAL.expr = n
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:468
		{
			s := &ast.StringLiteral{Value: yyDollar[1].str}
			s.Span = yyDollar[1].span
			yyVAL.expr = s
		}
	case 74:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:474
		{
			b := &ast.BoolLiteral{Value: true}
			b.Span = yyDollar[1].span
			yyVAL.expr = b
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:480
		{
			b := &ast.BoolLiteral{Value: false}
			b.Span = yyDollar[1].span
			yyVAL.expr = b
		}
	case 76:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:486
		{
			n := &ast.NullLiteral{}
			n.Span = yyDollar[1].span
			yyVAL.expr = n
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:492
		{
			a := &ast.ArrayLiteral{Elements: yyDollar[2].exprs}
			a.Span = yyDollar[1].span.Merge(yyDollar[3].span)
			yyVAL.expr = a
		}
	case 78:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./parser.y:498
		{
			a := &ast.ArrayLiteral{Elements: yyDollar[2].exprs}
			a.Span = yyDollar[1].span.Merge(yyDollar[4].span)
			yyVAL.expr = a
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:504
		{
			ol := &ast.ObjectLiteral{Properties: yyDollar[2].props}
			ol.Span = yyDollar[1].span.Merge(yyDollar[3].span)
			yyVAL.expr = ol
		}
	case 80:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./parser.y:509
		{
			ol := &ast.ObjectLiteral{Properties: yyDollar[2].props}
			ol.Span = yyDollar[1].span.Merge(yyDollar[4].span)
			yyVAL.expr = ol
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:514
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 82:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./parser.y:519
		{
			yyVAL.exprs = []ast.Expr{}
		}
	case 83:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:521
		{
			yyVAL.exprs = yyDollar[1].exprs
		}
	case 84:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:526
		{
			yyVAL.exprs = []ast.Expr{yyDollar[1].expr}
		}
	case 85:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:528
		{
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[3].expr)
		}
	case 86:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:533
		{
			p := ast.ObjectProperty{Key: yyDollar[1].str, Value: yyDollar[3].expr}
			p.Span = yyDollar[1].span.Merge(yyDollar[3].expr.GetSpan())
			yyVAL.prop = p
		}
	case 87:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:539
		{
			p := ast.ObjectProperty{Key: yyDollar[1].str, Value: yyDollar[3].expr}
			p.Span = yyDollar[1].span.Merge(yyDollar[3].expr.GetSpan())
			yyVAL.prop = p
		}
	case 88:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./parser.y:548
		{
			yyVAL.props = []ast.ObjectProperty{}
		}
	case 89:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:550
		{
			yyVAL.props = yyDollar[1].props
		}
	case 90:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./parser.y:555
		{
			yyVAL.props = []ast.ObjectProperty{yyDollar[1].prop}
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./parser.y:557
		{
			yyVAL.props = append(yyDollar[1].props, yyDollar[3].prop)
		}
	}
	goto yystack /* stack new state and value */
}
